// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlWAPANOxbK7G1Bl-LPh-i3_CT7OBKz8',
    appId: '1:1069161031261:web:a5883b0e660e112b198fb4',
    messagingSenderId: '1069161031261',
    projectId: 'anon-chat-46142',
    authDomain: 'anon-chat-46142.firebaseapp.com',
    storageBucket: 'anon-chat-46142.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA38WI3fQeD-a25cCAqxCnFuTRKw8KsSYg',
    appId: '1:1069161031261:android:f250335c932401f1198fb4',
    messagingSenderId: '1069161031261',
    projectId: 'anon-chat-46142',
    storageBucket: 'anon-chat-46142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALsYk0MCYzmHl4ISEbKb_hX0ZDWD8CzKg',
    appId: '1:1069161031261:ios:cb7965afacda2949198fb4',
    messagingSenderId: '1069161031261',
    projectId: 'anon-chat-46142',
    storageBucket: 'anon-chat-46142.appspot.com',
    iosClientId: '1069161031261-65u008n0k6pojbaqbdvtr07ksed7p7sa.apps.googleusercontent.com',
    iosBundleId: 'com.nayem.anonChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALsYk0MCYzmHl4ISEbKb_hX0ZDWD8CzKg',
    appId: '1:1069161031261:ios:cb7965afacda2949198fb4',
    messagingSenderId: '1069161031261',
    projectId: 'anon-chat-46142',
    storageBucket: 'anon-chat-46142.appspot.com',
    iosClientId: '1069161031261-65u008n0k6pojbaqbdvtr07ksed7p7sa.apps.googleusercontent.com',
    iosBundleId: 'com.nayem.anonChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHlWAPANOxbK7G1Bl-LPh-i3_CT7OBKz8',
    appId: '1:1069161031261:web:174324635b5e4de7198fb4',
    messagingSenderId: '1069161031261',
    projectId: 'anon-chat-46142',
    authDomain: 'anon-chat-46142.firebaseapp.com',
    storageBucket: 'anon-chat-46142.appspot.com',
  );

}